### PR TITLE
Remove zend dependencies + GitHub CI

### PR DESCRIPTION
**Pull request by UndefinedOffset**
It looks like the Zend dependencies referenced in #31 are not actually needed, this pull request removes them and also switches to GitHub Actions for CI. Also addresses #40 by also updating the `onelogin/php-saml` dependency to ^4.1.0.

### CODE REVIEW

**Review by satrun77 — APPROVED** [review]
Thanks 🙏

**Comment by UndefinedOffset** [comment]
@satrun77 any chance for a new tag? Also I notice I forgot to update the requirements in the readme it still talks about PHP 5.6 ;)

**Comment by satrun77** [comment]
@UndefinedOffset can you please make another PR to correct the readme file? Thanks :) 

I will test the latest changes and then tag it

**Comment by satrun77** [comment]
@UndefinedOffset tagged `2.1.1`

**Pull request merged**
