### PR TITLE
FIX: always validate received guid value 

### LINKED ISSUE #20: received GUID validity is not checked in all options
received guid validation is done only in case `expect_binary_nameid = true`

other scenarios allows to use any value

expected behavior: received value is always validated if it is valid GUID

### PR DESCRIPTION
**Pull request by JakubDolba**
always validate received guid value to be real guid as also DB field SAMLMemberExtension::GUID is configured to store GUID as varchar(50)

this fixes #20

### CODE REVIEW

**Review by robbieaverill — APPROVED** [review]

**Comment by LiamKearn** [comment]
I could be completely wrong but I have a feeling this is a breaking change from the latest tagged version in a few ways:
1. Previously other nameid formats (any/unspecified) were supported out of the box now only one is.
1. Previous sign-ons with then valid GUIDs are now completely locked out (No warning in the README/changelogs).
1. Out of the box installing silverstripe-saml advertises in its metadata that nameid format is unspecified (In way not really advertising anything) but given this change that should be modified to the appropriate standard.
1. Non-binary support in this module mentions Azure AD in which one of the popular nameid formats is the user.userprinciplename value in email address format (This is broken).

Our implementation does implement a custom SAMLHelper and that is instanced via the singleton pattern in this case so we can override `SAMLHelper::validGuid` for now. I think there is a case to be made about changing this before tagging a new release.

Suggested solutions:
- Grab the validation pattern from config.
- Release this gated with a config flag
- Add an extension point in `SAMLHelper::validGuid`
- Not sure about the underlying library interface over it but according to [this](https://www.samltool.com/generic_sso_res.php) the SAML response's nameid has a attribute reminding of its nameid format (validation should be based on this)

If this is not an Id10t error on my part and anyone else encounters this issue let me know and I'm make a PR 😄

**Comment by dhensby** [comment]
You do raise some very good points - if the nameid has no fixed format, we shouldn't just assume GUID and maybe a more robust or generic validation solution is required.

I think this change could probably be reverted or, at least, the docs updated as you suggest. The fact that the `SAMLHelper` is injectable does provide the flexibility needed, so I can understand it would be helpful to provide a way to *always* validate the name ID and to allow the developer to override that as required. But this approach does seem a bit too opinionated.

**Comment by madmatt** [comment]
Hey @LiamKearn, thanks for looking into this. I agree that this misses the mark a bit. I don't think you should default to assuming that the NameID is a GUID, there are plenty of places where this might not be true.

My suggestion would be to add the check behind a new `Config` flag on the `SAMLConfiguration` class, along with developer documentation, called something like `validate_nameid_as_guid`. For now, this should default to `true`, but it would give you a config flag that you can disable if your NameID is not a GUID.

This basically signals that either you're not using this module with ADFS/Azure AD, or that you've decided to use a different value as your unique user identifier (not recommended, but possible to do for sure).

Are you happy to raise this PR? If so, please feel free to do so, I'm happy to merge :)

**Comment by dhensby** [comment]
>For now, this should default to true, but it would give you a config flag that you can disable if your NameID is not a GUID.

Given this PR is only in master and hasn't been tagged/released (that I can see), so keeping the old behavior and making the UUID validation optional may be preferable if UUIDs are not a typical format for this field

**Pull request merged**
