### PR TITLE
Fix BackURL redirect with strict or lax session cookie security.

### PR DESCRIPTION
**Pull request by jareddreyerss**
See #55 PR for more context.

This is merely a cherry pick / copy of that commit but for the 2 branch so in theory should work in SS 4.x

### CODE REVIEW

**Comment by jareddreyerss** [comment]
Testing this in a proper environment that has SAML oauth to see if this fixes missing cookies #nomnomnom.

**Comment by jareddreyerss** [comment]
Tested the RelayState and it works perfecto. 
Doesn't fix missing cookies but having relaystate fed properly with query strings is immensely helpful.
@satrun77 mind reviewing that this ok going into 2 and tagging accordingly please? 🥺

**Comment by satrun77** [comment]
How urgent do you need this?

**Comment by jareddreyerss** [comment]
> How urgent do you need this?

Not super urgent but will be finished on client project by Friday. But it can live on the dev branch for now i guess.

**Review by satrun77 — APPROVED** [review]

**Pull request merged**
