### PR TITLE
Tests

### LINKED ISSUE #15: Increase code coverage significantly
The current code coverage is pretty abysmal, it would be great to improve that. I'll try and take a stab at this, but I'm not sure when I'll get to it, so I'm leaving this issue here for others to comment on and pick up if possible.

### PR DESCRIPTION
**Pull request by NightJar**
Includes API changes that require a `major` release. E.g. removal of dead methods, deprecated parameters from signatures, etc.
Mostly it just adds tests.

Closes #15

### CODE REVIEW

**Comment by madmatt** [comment]
This looks great, thanks @NightJar! I'll try to do a bit of a review shortly with a couple of other providers I have and see how it goes then look to merge and make a new release including these changes.

**Comment by NightJar** [comment]
Thanks @madmatt :)

The individual commit messages hold all the information & reasoning about the "impacting"* changes
(*totally non-impacting).

These often get overlooked in PRs so I thought I'd point it out.

**Comment by NightJar** [comment]
Also hold off on the new release after merging - there's more coming that depends on this 😅

**Comment by madmatt** [comment]
Sorry for the delay @NightJar, this look good - thanks! My only niggle is that I'm not a huge fan of IDE-specific attributes in the code (`#[Pure]`). Very minor though and not worth nitpicking so I'll merge now :)

**Pull request merged**
